apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-07-31T14:04:43Z
  labels:
    app: jay-1
  name: jay-1-service
  namespace: default
  resourceVersion: "2037"
  selfLink: /api/v1/namespaces/default/services/jay-1-service
  uid: 255c2573-b39c-11e9-80cd-42010af0000e
spec:
  clusterIP: 10.0.115.177
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: jay-1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
