apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2019-07-31T14:04:09Z
  generation: 2
  labels:
    app: jay-1
  name: jay-1
  namespace: default
  resourceVersion: "2890"
  selfLink: /apis/apps/v1/namespaces/default/deployments/jay-1
  uid: 110972b4-b39c-11e9-80cd-42010af0000e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jay-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jay-1
    spec:
      containers:
      - image: gcr.io/pe-training/nginx-new@sha256:b92e12ddda5f28a23208bb2d2388d97332676e133fbd033cb6a7cb29f4f3527b
        imagePullPolicy: IfNotPresent
        name: nginx-new-sha256
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-07-31T14:04:18Z
    lastUpdateTime: 2019-07-31T14:04:18Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-07-31T14:04:09Z
    lastUpdateTime: 2019-07-31T14:04:18Z
    message: ReplicaSet "jay-1-77cddd9fd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

